language: java

jdk:
  - oraclejdk8

script:
  - ./mvnw package cobertura:cobertura -Dmaven.javadoc.skip=true -Dgpg.skip=true

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file:
  - ./**/target/*.jar
  file_glob: true
  skip_cleanup: true
  on:
    tags: true

cache:
  directories:
  - $HOME/.m2
