language: java

jdk:
  - oraclejdk8
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

install:
  - ./mvnw package cobertura:cobertura -Dmaven.javadoc.skip=true -Dgpg.skip=true

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file:
  - dozermapper-spring-boot-starter/target/dozermapper-spring-boot-starter-*.jar
  - retrofit-spring-boot-starter/target/retrofit-spring-boot-starter-*.jar
  skip_cleanup: true
  on:
    tags: true

cache:
  directories:
  - $HOME/.m2
