language: java

jdk:
  - oraclejdk8

install:
  - ./mvnw package -Dmaven.javadoc.skip=true -Dgpg.skip=true

deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file:
  - dozermapper-spring-boot-starter/target/dozermapper-spring-boot-starter-0.0.1.jar
  - retrofit-spring-boot-starter/target/retrofit-spring-boot-starter-0.0.1.jar
  skip_cleanup: true

cache:
  directories:
  - $HOME/.m2